### ISSUE TITLE
Limiting splits of multipart administrative units

### ISSUE THREAD

**Issue by mjohnsonpa** [kosukeimai/redist#39]
I've been using redist.smc to run redistricting simulation on Pennsylvania's voting precincts while limiting splits of municipalities. We have a number of multipart municipalities in PA however, which cause an error (screen shot below)

This error only occurs when there are municipalities comprised of noncontiguous precincts.  It does not cause a problem if there is a multipart precinct that causes the municipality to also be multipart.  I have one workaround that appends the municipality names with part numbers and treats the noncontiguous parts as independent administrative units for the purposes of limiting municipality splits, but it would be great if there was a more inline way to deal with these issues when they arise, and especially if there was a way to do it that still treated the multipart municipality as a single entity.

![error](https://user-images.githubusercontent.com/78032449/105860990-3570b000-5fbc-11eb-8cfb-5202147cb6f1.png)

**Comment by christopherkenny** [comment]
Hello. Thanks for bringing this issue back up. This is a problem I've had before and solved it in a very similar way to you. Some counties in Florida, for example, are not contiguous, so we need to create a pseudo-county, by changing the label of the pieces. The difficulty that you're encountering is that, behind the scenes, SMC works with a county constraint by drawing a spanning tree within the county. If the county (or municipality in this case) is not connected, it can't draw a spanning tree. Due to this being one of the basic pieces of the algorithm, it would be incredibly difficult to change it in such a way that disconnected counties function as a single unit.  However, I messaged back and forth with @CoryMcCartan, who wrote most (if not all) of the redist.smc() code and we will try to get an automatic contiguity check in there for the future, to avoid the issue where it runs for a while and suddenly fails with that issue. 

As an short interim solution though, in the edgecut branch of redist, which is currently the most updated while we finish cleaning up new constraints in redist.mcmc, there is a new function called redist.county.relabel(), which will take your current county names and an adjacency list and create new names based on contiguous components. You can then pass the new names, which will look something like c("Adams". "Columbia", "Lancaster1", "Lancaster2", "Lancaster1",...) depending on the connected components of disconnected areas. If you want to take a look at the function, it's located [here.](https://github.com/kosukeimai/redist/blob/edgecut/R/counties.R)

Additionally, as a two-step solution to help treat things more as a single entity, in the past, I have done as follows:
1. Run SMC with a relabeled set.
2. Using the best map from smc$cdvec, based on whatever criteria you're using, use that as a seed for redist.mcmc(). If you run a relatively small number of iterations (think 150-250 depending on size of map,, but with multiple chains, probably 8 chains) using the county constraint with the original county names (not relabeled ones), the same population constraint, and your choice of compactness constraint, you can do a local search for solutions which improve on the county splitting. redist.mcmc uses a Gibbs based county split constraint, rather than the spanning tree one, so this doesn't have the same fundamental difficulty.

Feel free to send me a message if any of this is unclear or there's more difficulty!

To load in the edgecut branch of redist:
`remotes::install_github(repo = 'kosukeimai/redist', ref = 'edgecut')`

**Comment by mjohnsonpa** [comment]
Excellent, thank you so much.  That will solve my issue. I appreciate the quick and thorough response!
